### ISSUE TITLE
[REFACTOR] member-front-notice 연결 완료

### ISSUE THREAD

**Issue by EunjaeJo** [hi-sujung/msa-front#2]
📌 이슈 내용
로그인 멤버 정보를 프론트에 넘긴 후 해당 정보를 넣어 공지사항 불러오기 완료

💼 작업 목록
- [x] 로그인 화면 로컬 서버 연결
- [x] 로그인 방식 변경: token이 아닌 email을 파라미터로 전달
- [x] 공지사항 세부 정보 불러오기 함수 완성
- [x] 공지사항 좋아요 처리 함수 완성

**Comment by suhyenim** [comment]
이슈 확인했습니다 :)
