### ISSUE TITLE
[REFACTOR] notice-front-portfolio 통신 확인

### ISSUE THREAD

**Issue by EunjaeJo** [hi-sujung/msa-front#6]
📌 이슈 내용
자동 생성 포트폴리오(notice)가 사용자의 포트폴리오 목록(portfolio)에 추가되는지 확인

💼 작업 목록
- [x] 동일한 활동 중복 참여 처리 수정
- [x] 대외활동 리스트 화면에 '참여한 대외활동' 버튼 추가, 스크린 연결
- [x] notice, portfolio 각각 실행시켜서 자동 생성 포트폴리오 추가되는지 확인
- [x] 전체 애플리케이션 순서에 맞게 App.js 수정

**Comment by EunjaeJo** [comment]
![image](https://github.com/hi-sujung/msa-front/assets/80445063/593388ec-7fd9-420b-a8c5-762e348154da)
 대외활동 리스트 화면에 '참여한 대외활동' 버튼 추가, 스크린 연결

**Comment by suhyenim** [comment]
은재님 완전 짱이에요!!!!!!!!
